trigger:
- none

parameters:
- name: env
  displayName: Environment
  type: string
  default: d
  values:
  - d
  - p

- name: tag
  type: string
  default: dc01
  values:
  - dc01

variables:
  - group: addeploy-${{parameters.env}}

stages:
- stage: InstallOnPrem
  jobs:
  - deployment: InstallADDS
    displayName: 'Install ADDS'
    environment: 
      name: $(EnviormentName)
      resourceType: VirtualMachine
      tags: ${{parameters.tag}}
    strategy:
      runOnce:
        deploy:
          steps:
          #- checkout: self
          - powershell: |
              mkdir c:\$(Location)
              dir c:\